# Site settings
title: ASP.NET Web API for OData V4 Docs
email: odatafeedback@microsoft.com
description: > # this means to ignore newlines until "baseurl:"
  Complete documentations for ASP.NET Web API for OData V4
baseurl: "/WebApi" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

github_username:  odata

# Footer settings
footer:
  copyright: > #
    The materials available on this site are licensed
    as set forth <a href="https://github.com/OData/odata.github.io/blob/master/License.txt">here</a>.

# Build settings
markdown: kramdown
highlighter: pygments

permalink: /:title/
